name: Release

on:
  workflow_dispatch:
    inputs:
      version_id:
        description: 'Set the desired version id (e.g. 1.2.3dev)'
        required: true
        default: 'v1.0.0'


jobs:
  create_release:
    if: github.ref != 'refs/tags/v1'
    runs-on: ubuntu-latest
    name: Create Release

    steps:
      - uses: actions/checkout@v5
      - name: Create Release
        id: create_release
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          draft: true
          generateReleaseNotes: true